# Generated by Django 3.0.5 on 2020-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
                ('currentFreeCashFlow', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('CurrentMarketCap', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('GrowthRateYear1_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('GrowthRateYear4_6', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('GrowthRateYear7_10', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('DiscountRate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('FCF', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ExcessCash', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('TerminalMultiple', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
