# Generated by Django 3.0.5 on 2020-10-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='set_name',
            field=models.CharField(default='Tradebrain', max_length=100),
        ),
    ]
