# Generated by Django 3.0.5 on 2020-10-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_calc', '0002_stockdetail_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='CurrentMarketCap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='DiscountRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='ExcessCash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='FCF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='GrowthRateYear1_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='GrowthRateYear4_6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='GrowthRateYear7_10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='TerminalMultiple',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='currentFreeCashFlow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='set_name',
            field=models.CharField(max_length=100),
        ),
    ]
